name: Build and Deploy to Itch.io

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Makefile'
      - '.github/workflows/deploy-to-itch.yml'
      - 'assets/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y make cmake clang xorg-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libjansson-dev

      - name: Build project
        run: make -j

      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          sudo mv butler /usr/local/bin/

      - name: Authenticate Butler
        run: butler login
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}

      - name: Zip project
        run: |
          mkdir -p dist
          cp -r assets bombkurdistan dist/
          cd dist
          zip -r ../bombkurdistan.zip .

      - name: Upload to Itch.io
        run: butler push bombkurdistan.zip xielq/bomb-kurdistan:linux
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
